FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml ./
COPY shared ./shared
COPY scheduler ./scheduler

RUN uv pip install --system -r pyproject.toml

ENV PYTHONPATH=/app

CMD ["python3", "scheduler/scheduler.py"]
# CMD ["python3", "-m", "scheduler.scheduler"]